name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:

defaults:
  run:
    working-directory: C4C-admin-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "C4C-admin-ui/package-lock.json"

      - run: npm ci
      - run: npm run build
